<?php


/**
 * Модуль для работы с архивом
 */
function archive_menu()
{
    $items = array();
    $items['archive/import'] = array(
        'title' => 'Создание архива',
        'description' => 'Создание архива',
        'page callback' => 'archive_create',
        'access arguments' => array('administer archive module' ),
        'type' => MENU_CALLBACK,
    );
    $items['archive/student/all'] = array(
        'title' => 'Студенты',
        'description' => 'Список студентов',
        'page callback' => 'archive_all_students',
        'access arguments' => array('administer archive module' ),
        'type' => MENU_CALLBACK,
    );
    $items['archive/student'] = array(
        'title' => 'Студент',
        'description' => 'Студент',
        'page callback' => 'archive_student',
        'access arguments' => array('administer archive module' ),
        'type' => MENU_CALLBACK,
    );
    $items['archive/teacher'] = array(
        'title' => 'Преподаватель',
        'description' => 'Преподаватель',
        'page callback' => 'archive_teacher',
        'access arguments' => array('administer archive module' ),
        'type' => MENU_CALLBACK,
    );
    $items['archive/reviewer'] = array(
        'title' => 'Рецензент',
        'description' => 'Рецензент',
        'page callback' => 'archive_reviewer',
        'access arguments' => array('administer archive module' ),
        'type' => MENU_CALLBACK,
    );
    $items['archive/reviewer/all'] = array(
        'title' => 'Список рецензентов',
        'description' => 'Список рецензентов',
        'page callback' => 'archive_all_reviewers',
        'access arguments' => array('administer archive module' ),
        'type' => MENU_CALLBACK,
    );
    $items['archive/diplomas'] = array(
        'title' => 'Темы ВКР',
        'description' => 'Темы ВКР',
        'page callback' => 'archive_all_diplomas',
        'access arguments' => array('administer archive module' ),
        'type' => MENU_CALLBACK,
    );
    $items['archive/member_SEC'] = array(
        'title' => 'Член ГЭК',
        'description' => 'Член ГЭК',
        'page callback' => 'archive_member_sec',
        'access arguments' => array('administer archive module' ),
        'type' => MENU_CALLBACK,
    );
    $items['archive/additional_sections'] = array(
        'title' => 'Дополнительные разделы',
        'description' => 'Дополнительные разделы',
        'page callback' => 'archive_additional_sections',
        'access arguments' => array('administer archive module' ),
        'type' => MENU_CALLBACK,
    );
    $items ['archive/download/themes'] = array (
        'title' => 'Скачать список тем ВКР',
        'description' => 'Скачать список тем ВКР',
        'page callback'=>'archive_download_themes_doc',
        'access arguments' => array ('administer archive module' ),
        'type' => MENU_CALLBACK );
    $items ['archive/download/department/additional_sections'] = array (
        'title' => 'Скачать список студентов с доп разделом на кафедре',
        'description' => 'Скачать список студентов с доп разделом на кафедре',
        'page callback'=>'download_list_students_with_additional_sections_on_department',
        'access arguments' => array ('administer archive module' ),
        'type' => MENU_CALLBACK );
    $items ['archive/download/additional_section'] = array (
        'title' => 'Скачать список студентов с доп разделом',
        'description' => 'Скачать список студентов с доп разделом',
        'page callback'=>'download_list_students_with_additional_section',
        'access arguments' => array ('administer archive module' ),
        'type' => MENU_CALLBACK );
    $items ['archive/download/statistics/additional_section'] = array (
        'title' => 'Скачать статистику по доп разделам',
        'description' => 'Скачать статистику по доп разделам',
        'page callback'=>'create_excel_report',
        'access arguments' => array ('administer archive module' ),
        'type' => MENU_CALLBACK );
    return $items;
}

function archive_theme() {
    return array(
        'simple' => array(
            'render element' => 'form',
            'file' => 'archive.theme.inc',
        ),
        'diploma' => array(
            'render element' => 'form',
            'file' => 'archive.theme.inc',
        ),
        'reviewers' => array(
            'render element' => 'form',
            'file' => 'archive.theme.inc',
        ),
        'section' => array(
            'render element' => 'form',
            'file' => 'archive.theme.inc',
        ),
    );
}

function archive_permission()
{
    return array(
        'administer archive module' => array(
            'title' => t('Administer archive module'),
            'description' => t('Deny access to certain users.'),
        ),
    );
}

include 'archive_import.php';
include 'archive_all_students.php';
include 'archive_student.php';
include 'archive_teacher.php';
include 'archive.theme.inc';
include 'archive_diploma.php';
include 'archive_member_sec.php';
include 'archive_reviewer.php';
include 'archive_additional_section.php';
include 'archive_consultant.php';