<?php


/**
 * Модуль для работы с архивом
 */
function archive_menu()
{
    $items = array();
    $items['archive/import'] = array(
        'title' => 'Создание архива',
        'description' => 'Создание архива',
        'page callback' => 'archive_create',
        'access arguments' => array('administer archive module' ),
        'type' => MENU_CALLBACK,
    );
    $items['archive/student/all'] = array(
        'title' => 'Студенты',
        'description' => 'Список студентов',
        'page callback' => 'archive_all_students',
        'access arguments' => array('administer archive module' ),
        'type' => MENU_CALLBACK,
    );
    $items['archive/student'] = array(
        'title' => 'Студент',
        'description' => 'Студент',
        'page callback' => 'archive_student',
        'access arguments' => array('administer archive module' ),
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function archive_theme() {
    return array(
        'simple' => array(
            'render element' => 'form',
            'file' => 'archive.theme.inc',
        ),
    );
}

function archive_permission()
{
    return array(
        'administer archive module' => array(
            'title' => t('Administer archive module'),
            'description' => t('Deny access to certain users.'),
        ),
    );
}

include 'archive_import.php';
include 'archive_all_students.php';
include 'archive_student.php';
include 'archive.theme.inc';
